### PR TITLE
Quarto dependency

### PR DESCRIPTION
**Pull request by Farhan-Faisal**
- [x] Updated environment file (quarto, jupyter, notebook, tabulate)
- [x] Merged in changes from script branches
- [x] Changes to eda.py =>  (removed figure titles) 
- [x] Changes to model_evaluation.py => (used best_estimator for cross validation and changed table format)
- [x] Changed name of one script to clean_n_split.py
- [x] Added report.qmd, report.html, report.pdf
- [x] Created docs folder and copied over index.html
- [x] Made new docker file with fixed quarto permission issues

### CODE REVIEW

**Comment by Farhan-Faisal** [comment]
python download.py \
--id 186 \
--save_to data/wine_ex.csv

python validation_before_split.py \
--file_name wine_ex.csv \
--data_path ../data/

python clean_n_split_data.py \
--raw-data ../data/wine_ex.csv

python eda_n_correlation_check.py \
--train-file ../data/wine_train.csv \
--output-img ../results/figures \
--output-table ../results/tables

python preprocessing.py \
--pipe-to ../results/models

python model_evaluation_wine_predictor.py --train-data ../data/wine_train.csv \
--test-data ../data/wine_test.csv \
--pipeline-path ../results/models/wine_pipeline.pickle \
--table-to ../results/tables \
--plot-to ../results/figures

**Comment by Farhan-Faisal** [comment]
cd scripts
quarto render report.qmd --to pdf
quarto render report.qmd --to html

**Comment by Farhan-Faisal** [comment]
cp scripts/report.html ../docs
cd docs
mv report.html index.html

**Review by adrianl726 — APPROVED** [review]
crazy

**Comment by adrianl726** [comment]
Author names should be ordered by last names tho

**Comment by Farhan-Faisal** [comment]
Didn't notice it should be by last names :  ( 
Will fix it soon.

**Pull request merged**
