### PR TITLE
Ms4 makefile

### PR DESCRIPTION
**Pull request by Farhan-Faisal**
- Makefile added with multiline targets
- Data directory improved => raw and proc (MS1 fix)
- Updated README with makefile commands

### CODE REVIEW

**Review by dariakhv — COMMENTED** [review]
make file looks good!

**Review by dariakhv — CHANGES_REQUESTED** [review]
should we have make clean before, make all? to ensure the user is starting w a clean slate?

**Comment by Farhan-Faisal** [comment]
Good idea. Added make clean in readme before make all.

**Review by dariakhv — APPROVED** [review]
send it

**Pull request merged**
